[directory]
truncation_length = 5
truncate_to_repo = false
format = "[$path]($style)[$lock_symbol]($lock_style) "

[package]
disabled = false

[hostname]
ssh_only = false
format = "<[$hostname]($style)>"
trim_at = "-"
style = "bold dimmed white"
disabled = true

[username]
style_user = "bold dimmed blue"
show_always = false

[time]
time_format = "%H:%M"
format = "[$time]($style) "
style = "#9D9D9D"
disabled = false

[gcloud]
disabled = true
